### ISSUE TITLE
github 실제 활용해서 팀 프로젝트 진행해보기

### ISSUE THREAD

**Issue by WinteringAsch** [16-2-SKKU-OSS/16-2-OSS-D#10]
저희가 소개페이지를 만드는 것에 대해서, 교수님이 단순히 소개에서 그치지 않고 직접 활용해보는 것이 있으면 좋을것이라 하셨으니, 무엇인가 간단한 문제를 가져와서 다 같이 협업해서 해결해보는 것도 의미 있을 것 같습니다.

**Comment by jhoowy** [comment]
테트리스 같은 간단한 게임 만드는 건 어떨까요? github에 소스코드 올려서 다 같이 만들고, 만드는 과정 캡처해서 github 다루는 방법 소개하는 식으로..

**Comment by GneParkMarriedKorea** [comment]
프로그램의 완성도보다 팀프로젝트를 위해 깃허브를 어떻게 사용하면 되는지에 대해 집중해서 하면 좋을거같아요. 테트리스 같은 간단한 게임정도면 간단하고 딱 좋을것 같네요

**Comment by JaeheonKimm** [comment]
프로그램의 완성도보다 팀프로젝트를 위해 깃허브를 어떻게 사용하면 되는지에 대해 집중해서 하면 좋을거같아요. 테트리스 같은 간단한 게임정도면 간단하고 딱 좋을것 같네요

**Comment by prekmh** [comment]
프로젝트를 한다는 과정 하에, 각 카테고리를 어떻게 활용할지, 또는 프로젝트를 진행하는 데 있어서 참고한 사이트 등을 위키에 올리는 것도 괜찮을 것 같아요. 활용할 수 있는 기능을 되도록 많이 활용하는 것이 필요할 것 같습니다.
