### ISSUE TITLE
테트리스 이슈 - 다음에 나올 블록 표시

### ISSUE THREAD

**Issue by nyu531** [16-2-SKKU-OSS/16-2-OSS-D#21]
다음에 나올 블록 표시 기능을 구현하고 Close할 이슈입니다.

**Comment by JaeheonKimm** [comment]
다음에 나올 블록 표시기능 구현했습니다!

**Comment by jhoowy** [comment]
확인했습니다. 
수고하셨습니다!

**Comment by WinteringAsch** [comment]
![github_bug](https://cloud.githubusercontent.com/assets/23088321/20886205/446e222c-bb38-11e6-89af-eaac1704e265.png)
다음 블럭 모양이 이상한 모양이 나올 때가 있습니다

**Comment by JaeheonKimm** [comment]
아아 자꾸 코드 빼먹네요 다시 수정하겠습니다!

**Comment by JaeheonKimm** [comment]
`               // 다음블럭 생성
		removeBlock(next);
		next.type = rand() % 7;
		drawBlock(next);
`

이부분이 다음블럭을 지우고 다시 새로운 다음블럭을 출력해주는 부분인데
저는 테스트를 해봐도 버그가 발생하지 않았습니다. 

removeBlock 함수안에서 버그가 발생한건가요?

**Comment by WinteringAsch** [comment]
제가 디버깅을 제대로 할줄 몰라서 잘 모르겠습니다... 일단 저도 저 코드가 있는 상태에서 테스트했네요.
꾸준하게 발생하는건 아니고, 가끔 발생하는 것으로 보입니다.

**Comment by smahn9123** [comment]
저는 안 발생하는데... 이상하네요...

**Comment by WinteringAsch** [comment]
좀더 추가하자면, 다음 판 시작할때 한 칸이 미리 차있는 것처럼 보입니다.
![github_bug2](https://cloud.githubusercontent.com/assets/23088321/20887189/f715f536-bb3c-11e6-9cb1-5534bda89d75.png)
....라고 작성하고 있었는데, 처음 보는 모양도 뜨네요. 한 칸이 아니라, 한 모양이 남아있다고 봐야 될 듯 합니다.
짐작하자면, 종료된 판의 무언가가 남아있는게 아닐까 싶습니다.

**Comment by JaeheonKimm** [comment]
아 
게임오버가 나고 다시 시작할때 next block 을 remove해주지 않아서 그런것 같습니다.
게임오버가 났을때 removeblock(next)을 추가해줘야 할것 같습니다

**Comment by JaeheonKimm** [comment]
![image](https://cloud.githubusercontent.com/assets/23088492/20887852/b2f3793e-bb3f-11e6-85ea-cef2c8c2ae37.png)

저도 발생하네요 
게임오버 후 재시작했을 때 딱 발생합니다. 
재시작할때 전체화면을 Clear 하고 다시 시작하는 방법은 어떨까요?

**Comment by jhoowy** [comment]
다음 블럭 화면 버그 수정했습니다.

**Comment by JaeheonKimm** [comment]
기능이 추가되었으므로 이슈를 닫겠습니다!
